// @vitest-environment jsdom
import { createRequire } from 'node:module'
import { resolve } from 'node:path'
import { createElement, useState, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import ts from 'typescript'
import { describe, expect, it, vi } from 'vitest'
import { DiagnosticCode, transformSourceFile } from '../src/index.js'

const require = createRequire(import.meta.url)

const compile = (source: string) => {
  const result = transformSourceFile('src/View.ts', source)
  if (!result.ok) throw new Error(JSON.stringify(result.diagnostics, null, 2))
  return result.code
}

/** Type-strips and evaluates generated TSX, returning its exports. */
const load = (code: string, modules: Record<string, unknown> = {}) => {
  const { outputText } = ts.transpileModule(code, {
    compilerOptions: {
      jsx: ts.JsxEmit.ReactJSX,
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
    },
  })
  const exports: Record<string, any> = {}
  const load = (name: string) => modules[name] ?? require(name)
  new Function('exports', 'require', outputText)(exports, load)
  return exports
}

const view = `
import type { Html, HtmlBuilder } from 'foldkit/html'
import { Message, type Model } from './message'

const row = (label: string, h: HtmlBuilder<Message>): Html =>
  h.li([h.Class('row'), h.OnClick(Message.Picked({ label }))], [label])

export const view = (model: Model, h: HtmlBuilder<Message>): Html =>
  h.form(
    [h.Id('form'), h.OnSubmit(Message.Submitted()), h.Style({ 'background-color': 'red' })],
    [
      h.input([h.Value(model.query), h.OnInput(query => Message.Typed({ query })), h.AriaLabel('Query')]),
      h.button([h.Type('submit'), h.Disabled(model.query === '')], ['Save']),
      model.items.length === 0 ? h.p([], ['Empty']) : h.ul([], model.items.map(item => row(item, h))),
    ],
  )
`

describe('transformSourceFile', () => {
  it('emits deterministic TSX for the supported subset', () => {
    const code = compile(view)
    expect(compile(view)).toBe(code)
    expect(code).toMatchInlineSnapshot(`
      "// @generated by foldkit-react-codegen from src/View.ts. Do not edit.
      import type { ReactNode } from "react";
      import { Message, type Model } from './message';
      const row = (label: string, dispatch: (message: Message) => void): ReactNode => (<li className={'row'} onClick={() => dispatch(Message.Picked({ label }))}>{label}</li>);
      export const view = (model: Model, dispatch: (message: Message) => void): ReactNode => (<form id={'form'} onSubmit={event => {
          event.preventDefault();
          dispatch(Message.Submitted());
      }} style={{ backgroundColor: 'red' }}><input value={model.query} onChange={event => dispatch((query => Message.Typed({ query }))(event.currentTarget.value))} aria-label={'Query'}/><button type={'submit'} disabled={model.query === ''}>Save</button>{model.items.length === 0 ? (<p>Empty</p>) : (<ul>{model.items.map(item => row(item, dispatch))}</ul>)}</form>);
      "
    `)
  })

  it('emits TSX that type-checks against React', () => {
    // jsdom replaces import.meta.url's scheme, so resolve from the package directory.
    const root = `${resolve(process.cwd(), 'packages/react-codegen')}/`
    const files: Record<string, string> = {
      [`${root}virtual/View.tsx`]: compile(view),
      [`${root}virtual/message.ts`]: `export type Model = { readonly query: string; readonly items: ReadonlyArray<string> }
export type Message = { readonly _tag: 'Picked'; readonly label: string } | { readonly _tag: 'Submitted' } | { readonly _tag: 'Typed'; readonly query: string }
export const Message = {
  Picked: (fields: { readonly label: string }): Message => ({ _tag: 'Picked', ...fields }),
  Submitted: (): Message => ({ _tag: 'Submitted' }),
  Typed: (fields: { readonly query: string }): Message => ({ _tag: 'Typed', ...fields }),
}
`,
    }
    const options: ts.CompilerOptions = {
      jsx: ts.JsxEmit.ReactJSX,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      target: ts.ScriptTarget.ES2022,
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      types: [],
    }
    const host = ts.createCompilerHost(options)
    const normalize = (name: string) => name.replace(/\\/g, '/')
    const virtual = (name: string) =>
      Object.entries(files).find(([path]) => normalize(path) === normalize(name))?.[1]
    const { fileExists, readFile, getSourceFile } = host
    host.fileExists = name => virtual(name) !== undefined || fileExists.call(host, name)
    host.readFile = name => virtual(name) ?? readFile.call(host, name)
    const { directoryExists } = host
    host.directoryExists = name =>
      normalize(name).endsWith('/virtual') || (directoryExists?.call(host, name) ?? false)
    host.getSourceFile = (name, language) => {
      const text = virtual(name)
      return text === undefined
        ? getSourceFile.call(host, name, language)
        : ts.createSourceFile(name, text, language)
    }
    const program = ts.createProgram([`${root}virtual/View.tsx`], options, host)
    const errors = ts
      .getPreEmitDiagnostics(program)
      .map(diagnostic => ts.flattenDiagnosticMessageText(diagnostic.messageText, ' '))
    expect(errors).toEqual([])
  })

  it('renders and dispatches like the Foldkit view', async () => {
    const Message = {
      Picked: (fields: { label: string }) => ({ _tag: 'Picked', ...fields }),
      Submitted: () => ({ _tag: 'Submitted' }),
      Typed: (fields: { query: string }) => ({ _tag: 'Typed', ...fields }),
    }
    const generated = load(compile(view), { './message': { Message } })
    const dispatched: Array<{ _tag: string }> = []

    const App = () => {
      const [model, setModel] = useState({ query: '', items: ['a', 'b'] })
      const dispatch = (message: any) => {
        dispatched.push(message)
        if (message._tag === 'Typed') setModel(current => ({ ...current, query: message.query }))
      }
      return generated.view(model, dispatch) as ReactNode
    }
    const container = document.createElement('div')
    document.body.appendChild(container)
    const root = createRoot(container)
    root.render(createElement(App))

    await vi.waitFor(() => expect(container.querySelectorAll('li.row')).toHaveLength(2))
    const form = container.querySelector('form')!
    expect(form.id).toBe('form')
    expect(form.style.backgroundColor).toBe('red')
    const button = container.querySelector('button')!
    expect(button.disabled).toBe(true)
    expect(container.querySelector('input')!.getAttribute('aria-label')).toBe('Query')

    ;(container.querySelectorAll('li.row')[1] as HTMLElement).click()
    expect(dispatched.at(-1)).toEqual({ _tag: 'Picked', label: 'b' })

    // React listens for the native input event through the value setter it tracks.
    const input = container.querySelector('input')!
    const setValue = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!
    setValue.call(input, 'hi')
    input.dispatchEvent(new Event('input', { bubbles: true }))
    await vi.waitFor(() => expect(button.disabled).toBe(false))
    expect(dispatched.at(-1)).toEqual({ _tag: 'Typed', query: 'hi' })

    const submit = new Event('submit', { bubbles: true, cancelable: true })
    form.dispatchEvent(submit)
    expect(submit.defaultPrevented).toBe(true)
    expect(dispatched.at(-1)).toEqual({ _tag: 'Submitted' })
    root.unmount()
  })

  it.each([
    ['a Mount', `h.div([h.OnMount(mount)], [])`, DiagnosticCode.UnsupportedAttribute, 'h.OnMount'],
    [
      'a native change event',
      `h.input([h.OnChange(v => M.A(v))])`,
      DiagnosticCode.UnsupportedAttribute,
      'h.OnChange',
    ],
    [
      'a Submodel',
      `h.submodel({ slotId: 'x' } as any)`,
      DiagnosticCode.UnsupportedBuilder,
      'h.submodel',
    ],
    [
      'computed attributes',
      `h.div(attributes, [])`,
      DiagnosticCode.DynamicAttributes,
      'array literal',
    ],
    [
      'a spread attribute',
      `h.div([...attributes], [])`,
      DiagnosticCode.DynamicAttributes,
      'inline',
    ],
    [
      'an attribute outside an element',
      `h.Class('x')`,
      DiagnosticCode.DynamicAttributes,
      'h.Class',
    ],
    [
      'click options',
      `h.button([h.OnClick(M.A(), { propagation: 'Stop' })], [])`,
      DiagnosticCode.UnsupportedAttributeArgument,
      'options',
    ],
    [
      'a stored builder',
      `(() => { const b = h; return b.div([], []) })()`,
      DiagnosticCode.EscapedBuilder,
      'helper view',
    ],
  ])('rejects %s with a located diagnostic', (_, body, code, fragment) => {
    const source = `import type { Html, HtmlBuilder } from 'foldkit/html'\nexport const view = (h: HtmlBuilder<M>): Html =>\n  ${body}\n`
    const result = transformSourceFile('src/View.ts', source)
    expect(result.ok).toBe(false)
    const [diagnostic] = result.diagnostics
    expect(diagnostic).toMatchObject({ code, fileName: 'src/View.ts', line: 3 })
    expect(diagnostic!.message).toContain(fragment)
  })

  it('names ARIA attributes, escapes entity text, and keeps a local Html type', () => {
    const code = compile(`import type { HtmlBuilder } from 'foldkit/html'
type Html = { readonly local: true }
export const view = (h: HtmlBuilder<M>, extra: Html) =>
  h.p([h.AriaLabelledBy('title'), h.AriaHasPopup('true')], ['Tom &amp; Jerry', 'plain'])
`)
    expect(code).toContain('aria-labelledby={')
    expect(code).toContain('aria-haspopup={')
    expect(code).toContain(`{'Tom &amp; Jerry'}`)
    expect(code).toContain(`{'Tom &amp; Jerry'}plain</p>`)
    expect(code).toContain('extra: Html')
  })

  it('leaves a module without views unchanged apart from the header', () => {
    const result = transformSourceFile(
      'src/util.ts',
      'export const add = (a: number, b: number) => a + b\n',
    )
    expect(result.ok && result.code).toBe(
      '// @generated by foldkit-react-codegen from src/util.ts. Do not edit.\nexport const add = (a: number, b: number) => a + b;\n',
    )
  })
})
