// @vitest-environment jsdom
/**
 * `entry.ts` on the real runtime, in the two pages it meets: one the build
 * rendered, which it takes over in place, and the dev server's empty
 * `index.html`, which it draws.
 */
import { join } from 'node:path'
import { afterEach, beforeEach, expect, test, vi } from 'vitest'

import { STYLESHEET_ATTRIBUTE } from '../src/style.js'
import { generate, loading, template } from './helpers.js'

// The build id `entry.ts` reads of itself: its own address, a file path under Vitest.
const entry = join(import.meta.dirname, '../src/entry.ts')

beforeEach(() => {
  vi.resetModules()
  vi.stubGlobal('requestAnimationFrame', (callback: FrameRequestCallback) =>
    setTimeout(() => callback(performance.now()), 0),
  )
  vi.stubGlobal('cancelAnimationFrame', clearTimeout)
})

afterEach(() => {
  vi.unstubAllGlobals()
  document.head.replaceChildren()
  document.body.replaceChildren()
})

/** Puts `html` in the document at `path`, as the browser loads it, and runs `entry.ts`. */
const open = async (html: string, path: string) => {
  const page = new DOMParser().parseFromString(html, 'text/html')
  document.head.replaceChildren(...Array.from(page.head.childNodes))
  document.body.replaceChildren(...Array.from(page.body.childNodes))
  window.history.replaceState(null, '', path)
  await import('../src/entry.js')
}

const waitFor = (assertion: () => void) => vi.waitFor(assertion, { timeout: 3_000 })

const heading = (): string | null | undefined => document.getElementById('page-title')?.textContent

const link = (name: string): HTMLAnchorElement => {
  const found = Array.from(document.querySelectorAll('a')).find(a => a.textContent === name)
  if (found === undefined) throw new Error(`no link named ${name}`)
  return found
}

const button = (): HTMLButtonElement => {
  const found = document.querySelector('button')
  if (found === null) throw new Error('no button')
  return found
}

test('takes a generated page over in place, and it counts and navigates', async () => {
  const [, about] = await generate(loading(entry))
  const errors = vi.spyOn(console, 'error')
  await open(about.html, '/about')
  const served = document.getElementById('page-title')
  const nav = document.querySelector('nav')

  link('Home').click()
  await waitFor(() => expect(heading()).toBe('Statically generated home'))
  expect(document.title).toBe('Home | Static Generation | Foldkit')
  expect(window.location.pathname).toBe('/')
  // The server's nodes were adopted, not drawn again.
  expect(document.querySelector('nav')).toBe(nav)
  expect(served?.isConnected).toBe(true)

  button().click()
  await waitFor(() => expect(button().textContent).toBe('Count: 1'))
  button().click()
  await waitFor(() => expect(button().textContent).toBe('Count: 2'))

  link('About').click()
  await waitFor(() => expect(heading()).toBe('Statically generated about page'))
  expect(errors).not.toHaveBeenCalled()
  expect(document.querySelectorAll(`style[${STYLESHEET_ATTRIBUTE}]`)).toHaveLength(1)
})

test('refuses a page generated by another build', async () => {
  const [home] = await generate(loading('/assets/index-other.js'))
  await open(home.html, '/')
  await waitFor(() => expect(document.body.inert).toBe(true))
})

test('draws the dev server’s empty page itself, with the stylesheet installed once', async () => {
  await open(template, '/about')
  await waitFor(() => expect(heading()).toBe('Statically generated about page'))
  expect(document.title).toBe('About | Static Generation | Foldkit')
  expect(document.querySelectorAll(`style[${STYLESHEET_ATTRIBUTE}]`)).toHaveLength(1)
})

test('draws an address no page was generated for as not found', async () => {
  await open(template, '/missing')
  await waitFor(() => expect(heading()).toBe('Not found'))
  expect(document.title).toBe('Not Found | Static Generation | Foldkit')
  expect(document.body.textContent).toContain('No statically generated page exists for /missing.')
})
