/**
 * What `pnpm dev` starts with: eight published posts and two published pages,
 * imported by the CMS (`cms.import`), which publishes each as an author's publish
 * would: the application's own create handler writes the row, and the entry and
 * its first revision follow. The scripted run starts empty and builds its own.
 */
import { Effect } from 'effect'
import { SOURCE } from './domain.js'

/** What `cms.import` takes, less whom it is imported as, which the server fixes. */
interface Imported {
  readonly type: 'posts' | 'pages'
  readonly values: unknown
  readonly at: Date
  readonly entry: string
}

interface Seeded {
  /** The name the rest of the seed knows it by; the row's id is the create handler's. */
  readonly key: string
  readonly values: Readonly<Record<string, unknown>>
  readonly daysAgo: number
}

const post = (
  key: string,
  title: string,
  slug: string,
  excerpt: string,
  body: ReadonlyArray<string>,
  daysAgo: number,
): Seeded => ({
  key,
  values: { title, slug, excerpt, cover: '', body: body.join('\n') },
  daysAgo,
})

const node = (
  block: string,
  props: Readonly<Record<string, unknown>>,
  regions: Readonly<Record<string, ReadonlyArray<string>>> = {},
  appearance?: Readonly<Record<string, string>>,
) => ({ block, props, regions, ...(appearance === undefined ? {} : { appearance }) })

/** The home page, with the featured post by the id its import gave it. */
const home = (featured: string) => ({
  format: 1,
  roots: ['hero', 'latest', 'featured', 'about'],
  nodes: {
    hero: node(
      'Hero',
      {
        eyebrow: 'Foldkit Plus, explained',
        title: 'A blog that explains itself',
        lead: 'Posts on the CMS, the page builder and the packages under them, written and published in the studio they describe.',
      },
      { actions: ['read', 'code'] },
      { tone: 'accent' },
    ),
    read: node(
      'Button',
      { label: 'Read the blog', href: '/site/blog' },
      {},
      { tone: 'neutral', variant: 'solid' },
    ),
    code: node(
      'Button',
      { label: 'Read the code', href: SOURCE },
      {},
      { tone: 'neutral', variant: 'outline' },
    ),
    latest: node('Section', { heading: '' }, { body: ['posts'] }),
    posts: node('PostList', { heading: 'Latest writing', count: 3 }),
    featured: node('Section', { heading: '' }, { body: ['feature'] }, { tone: 'muted' }),
    feature: node('FeaturedPost', { post: featured }),
    about: node(
      'Section',
      { heading: 'What this is' },
      { body: ['aboutText', 'note'] },
      { width: 'narrow' },
    ),
    aboutText: node('Text', {
      body: 'This site is the demo of Foldkit Plus: the posts are written in its CMS, and this page was built with its page builder.\n\nEvery page is a document of Blocks. Authors arrange them; the site draws them with its own views.',
    }),
    note: node('Callout', {
      title: 'Try it',
      body: 'Open the page editor, change this page, and publish it. The site shows what was published, and nothing else.',
    }),
  },
})

const about = {
  format: 1,
  roots: ['hero', 'story'],
  nodes: {
    hero: node(
      'Hero',
      { eyebrow: 'About', title: 'A demo you can take apart', lead: '' },
      {},
      { tone: 'plain', align: 'center' },
    ),
    story: node('Section', { heading: '' }, { body: ['columns', 'quote'] }),
    columns: node('Columns', {}, { left: ['text'], right: ['image'] }, { ratio: '2:1' }),
    text: node('Text', {
      body: 'This site, its studio and its server are one example application of Foldkit Plus. Each post here explains a part of it: the CMS, the page builder, how pages are stored, how data moves, and how the views are styled.\n\nThe code is on GitHub, under examples/cms in the foldkit-plus repository. The Code link at the top of every page goes there.',
    }),
    image: node('Image', {
      src: '/images/desk.svg',
      alt: 'A desk with a lamp and an open notebook',
      caption: 'Where the drafts happen.',
    }),
    quote: node('Quote', {
      text: 'Make it work, make it right, make it fast.',
      cite: 'Kent Beck',
    }),
  },
}

/**
 * The blog: posts that explain how this demo is made. A body is lines, joined:
 * a blank line between parts, `## ` for a heading, `- ` for a list, and three
 * backticks around code (see `bodyOf` in `site.ts`).
 */
const posts: ReadonlyArray<Seeded> = [
  post(
    'post-crud',
    'Admin screens, joined not generated',
    'admin-screens-joined-not-generated',
    'An editor that joins a form to its mutation, a list that joins a query to a selection, a remover that asks first: how foldkit-crud builds management screens without generating anything.',
    [
      'The list of posts in the studio is a table: each post’s title and state, a search box',
      'above it and a tab for the archive. It is `foldkit-crud`, drawn by `foldkit-mixins-crud`.',
      'Crud is one of the smallest packages here, because it owns almost nothing.',
      '',
      '## Joined, not generated',
      '',
      'A tool that makes an admin screen from a table has to guess: which fields, in which',
      'order, and what a save does. Crud does not guess. It joins parts the application',
      'already declared, and each keeps its own job:',
      '',
      '- a form says what may be entered, and when it is valid (`foldkit-form`);',
      '- a mutation says what a save does on the server (`foldkit-remote`);',
      '- a query says what a list holds, and a selection which of its fields are shown (`foldkit-entity`);',
      '- Remote’s store holds what was loaded, and whether a save is pending, done or failed.',
      '',
      'What Crud adds is what sits between them: which record is open, whether its value',
      'has been put in the form yet, and which save is this screen’s.',
      '',
      '## A list',
      '',
      'A list is a query and a selection. The studio’s list of posts:',
      '',
      '```ts',
      "export const WorklistList = Crud.list('Worklist', {",
      '  query: Cms.Entries,',
      '  selection: EntryRow,',
      '})',
      '',
      'export const Worklist = WorklistList.at({',
      '  data: Data,',
      '  input: (model: Model) =>',
      '    Option.some({',
      '      type: Posts.name,',
      '      search: model.search,',
      '      archived: model.archived,',
      '    }),',
      '})',
      '```',
      '',
      'The query’s input is read from the Model, so the search and the archive tab are',
      'the application’s own state, and when either changes, the list needs another page',
      'and Remote reads it. A list keeps no state of its own. Its pages are in Remote’s',
      'store: `Worklist.page(model)` reads them, and `Worklist.more(model)` asks for',
      'the next. A read that failed is not retried by itself: `Worklist.refresh(model)`',
      'is the retry, and the table can offer it as a button.',
      '',
      '## Drawn as a table',
      '',
      '`foldkit-mixins-crud` draws a list as an accessible table. Its columns come from the',
      'selection, each labelled by its Schema’s title, and each cell is drawn by its',
      'field’s Display: text, a number, yes or no, a reference. The CMS adds a Display',
      'of its own, the coloured state badge, and hands its renderer to the table (trimmed):',
      '',
      '```ts',
      'WorklistTable(',
      '  {',
      '    page: Worklist.page(model),',
      '    onOpen: row => Message.OpenedEntry({ entry: row.id }),',
      '    renderers: Cms.displayRenderers(),',
      "    words: { empty: 'Nothing yet. Start a post.' },",
      '  },',
      '  h,',
      ')',
      '```',
      '',
      'Opening a row is a Message the application passes in, so the table never decides',
      'what opening means. While the first page loads, the table’s status line is marked',
      'busy, and this site shows it only if the wait is long. An empty list says so in',
      'words the application chose.',
      '',
      '## An editor',
      '',
      '`Crud.editor` joins a form to the mutation its value feeds:',
      '',
      '```ts',
      'const Editor = Crud.editor(',
      "  'PostEditor',",
      '  { form: EditPostForm, mutation: EditPostMutation },',
      ')',
      '```',
      '',
      'Opening a record empties the form and asks Remote for the fields the form edits.',
      'When they arrive, the form is filled. A valid submit becomes the mutation, and',
      'the editor’s status says where it is: Loading, Editing, Saving, Saved, or',
      'SaveFailed with the reason. Remote holds the value and the save, and the form',
      'holds the drafts. The editor holds only which record is open and which save',
      'is its own.',
      '',
      'This blog’s editor is `foldkit-cms`’s rather than Crud’s, because a post saves',
      'to a draft beside its row, not to the row. It has the same shape (open, load,',
      'fill, submit, report) with drafts, publishing and revisions added.',
      '',
      '## Deleting, details and pickers',
      '',
      'Crud has three more parts, which this demo does not need:',
      '',
      '- `Crud.remover` deletes through a mutation with a yes in between. It asks, waits for Confirmed or Cancelled, and reports Deleting, Deleted or DeleteFailed. When the server says what it deleted, Remote drops it from every list, and an editor open on it reads NotFound.',
      '- `Crud.detail` reads one record through a selection, to show as labelled fields.',
      '- `Crud.options` feeds a form’s relation pickers from lists: an author picker from a list of authors. A picker that searches hands its search text to the list as its input.',
      '',
      'Each is state or a reading, like the list and the editor. None draws anything,',
      'and none keeps a copy of what Remote holds.',
    ],
    0,
  ),
  post(
    'post-form',
    'Forms that know what they submit',
    'forms-that-know-what-they-submit',
    'A form built from the input its operation accepts: drafts that do not decode yet, checks that ask the server, and a value handed over only once it is valid. How foldkit-form works.',
    [
      'Every post on this blog was written in a form: the title, the address, the excerpt',
      'and the body you are reading. The page builder is a form too, with the whole page',
      'as one of its fields. Both are `foldkit-form`.',
      '',
      '## Built from what is submitted',
      '',
      'A form here is not a list of fields written by hand. It is built from the input',
      'of the operation it feeds. A post is published by `CreatePost` or `UpdatePost`,',
      'and both take the same input:',
      '',
      '```ts',
      'export const PostInput = Schema.Struct({',
      '  title: Post.fields.title.schema,',
      '  slug: Post.fields.slug.schema,',
      '  excerpt: Post.fields.excerpt.schema,',
      '  cover: Post.fields.cover.schema,',
      '  body: Post.fields.body.schema,',
      '})',
      '```',
      '',
      'The form is made from that same Schema, read through the Entity, so each key',
      'knows which field it writes (trimmed):',
      '',
      '```ts',
      "export const PostForm = Form.make('PostForm', Entity.input(Post, PostInput), {",
      '  inputs: {',
      "    slug: Cms.slug('title', { prefix: '/blog/' }),",
      '    title: Input.multiline(),',
      '    excerpt: Input.multiline(),',
      '    body: Input.multiline(),',
      '  },',
      '})',
      '```',
      '',
      'The rest comes from the Schema. A key’s label and hint are its `title` and',
      '`description`. A key is required exactly when its Schema refuses an empty value:',
      'the title is, because it is checked with `isMinLength(1)`, and the cover is not.',
      'The control is chosen from the key’s shape (a text field, a number, a toggle,',
      'a select among a few values, a picker for a relation) unless `inputs` names one.',
      '',
      '## A draft is not a value',
      '',
      'What a control holds is a draft: the text as it is typed. A number being typed is',
      'text, and `1.` is a fine draft that is not a number yet. The form keeps each draft',
      'in the Model with its state: not checked yet, valid, invalid with a reason, or',
      'waiting on a check.',
      '',
      'Each key is checked against its own part of the input as it changes, so a mistake',
      'is said where it is made. A submit asks for the whole: every key valid and the input',
      'decoded. Then the form hands its parent one value, typed as the operation’s input.',
      'What happens next is the parent’s. The form has no “submitting” state, because it',
      'submits nothing itself.',
      '',
      '## Checks that ask the server',
      '',
      'Some rules only a server can answer. A post’s address must not be taken by another,',
      'so the slug has a check that asks:',
      '',
      '```ts',
      "PostForm.pipe(Form.checks({ slug: Cms.addressFree('posts') }))",
      '```',
      '',
      'A check runs after the key’s own Schema passes, with the decoded value. Meanwhile',
      'the key reads as waiting. An answer that arrives after a newer edit is dropped,',
      'and a submit made during a check goes out when the check passes. A post may keep',
      'its own address, because the form knows which post it is editing.',
      '',
      '## A key that follows another',
      '',
      'Type a title in the studio, and the address fills itself in. `Cms.slug` is built on',
      '`Input.following`: the address is written from the title until the author writes',
      'it themselves, and emptying it hands it back to the title.',
      '',
      '## A control with a Model of its own',
      '',
      'Most controls hold text. The page builder holds a page, a selection and an undo',
      'history. `Input.bundle` makes any Bundle a control: its Model is the key’s draft,',
      'its Messages are the form’s, and the form counts a Message as an edit only when',
      'it changes the value. The page form uses one:',
      '',
      '```ts',
      "export const PageForm = Form.make('PageForm', Entity.input(Page, PageInput), {",
      '  inputs: {',
      "    slug: Cms.slug('title', { prefix: '/' }),",
      '    document: PageBuilder.inputWith(BuilderView.submodel(PageEditing)),',
      '  },',
      '})',
      '```',
      '',
      'So selecting a block is not an edit and saves nothing. Dropping one is, and the CMS',
      'saves it as it saves a typed word.',
      '',
      '## Drawn from outside',
      '',
      'The form draws nothing. `foldkit-mixins-form` draws it as plain HTML with every part',
      'a named Slot: each label tied to its field, `aria-invalid` and `aria-describedby` set,',
      'and errors announced. This blog gives it the look of a page to write on by attaching',
      'Styles to those Slots. Its placeholders (“Post title”, “Begin writing your post…”)',
      'are a Behavior attached the same way, not a fork of the view.',
    ],
    2,
  ),
  post(
    'post-how-it-is-made',
    'How this site is made',
    'how-this-site-is-made',
    'A blog, its studio and its server, built from Foldkit Plus packages: what each part owns, and where to read the code.',
    [
      'This blog is the demo of Foldkit Plus, a set of packages for Foldkit applications.',
      'Everything you can do here, from writing a post to building this page from blocks,',
      'runs on a few ideas, and the posts on this blog explain them one at a time.',
      '',
      '## Three applications, one server',
      '',
      'The demo is three Foldkit applications:',
      '',
      '- the studio’s posts, at `/`, where posts are written, scheduled and published;',
      '- the studio’s pages, at `/pages`, where pages like the home page are built from blocks;',
      '- the site, at `/site`, which is what a visitor reads.',
      '',
      'Each is one state machine: a Model, a union of the Messages that can happen,',
      'and one `update` that turns a Model and a Message into the next Model.',
      'Nothing on screen is kept anywhere else.',
      '',
      'All three talk to one server. On a developer’s machine, `pnpm dev` runs it in Node.',
      'In this published demo it runs in your browser tab: the same server code,',
      'over SQLite compiled to WebAssembly, with its database saved in your browser.',
      'Nothing you write leaves your browser, and `?reset` in the address starts afresh.',
      '',
      '## Who owns what',
      '',
      'Most bugs in an interface come from two places that believe different things',
      'about one fact. So each package here starts by naming the owner of a fact:',
      '',
      '- A post’s published text is the server’s. The client keeps a copy in its Model, which `foldkit-remote` fills, and may throw away and ask for again.',
      '- A draft is kept beside the published row, never in it, so a visitor cannot read unfinished work. That is `foldkit-cms`.',
      '- A page is data: a document of blocks stored in a field, which `foldkit-composition` checks and `foldkit-builder` edits.',
      '- The search and the tab of the studio’s list are the application’s own, and the address only shows them, through `foldkit-mirror`. The open post and the builder’s panel are the editor’s and the builder’s, and the address asks them through their Messages. Either way, a reload comes back to them.',
      '- The look belongs to the views: `foldkit-mixins` attaches styles to named parts of a view, with no stylesheet to keep in step.',
      '',
      '## Sit in another chair',
      '',
      'The studio has three chairs. Wren is a writer, who can write and save but not publish.',
      'Edda is an editor, who can publish. A visitor sees only the site.',
      'Switching chairs shows a rule every package keeps: what you may do is decided',
      'by the server, not by which buttons are drawn. If a writer asks to publish anyway,',
      'the server refuses.',
      '',
      '## Read the code',
      '',
      'The whole demo is in the repository under `examples/cms`: the studio in `app.ts`,',
      '`pageApp.ts` and their views, the site in `siteApp.ts` and `siteView.ts`,',
      'and the server in `server.ts`. The Code link at the top of this site goes there.',
    ],
    1,
  ),
  post(
    'post-drafts',
    'Saving is not publishing',
    'saving-is-not-publishing',
    'Drafts beside the row, revisions kept, and a state nobody stores: how foldkit-cms gives this blog an editor that saves as you type and publishes only when asked.',
    [
      'Open a post in the studio and type. Pause, and the status line says “Draft saved.”',
      'Nothing a visitor reads has changed. Press Publish, and it has.',
      'That split is most of what `foldkit-cms` does, and it takes little.',
      '',
      '## A draft is an unsent form',
      '',
      'The blog’s posts live in an ordinary `posts` table, and the CMS adds no columns to it.',
      'A draft is kept beside the row, in a table of the CMS’s own, and it holds what',
      'the post’s form holds: the saved input of the mutation that would publish it.',
      '',
      'So publishing is not a special operation. It is the application’s own mutation,',
      '`CreatePost` or `UpdatePost`, run with the draft’s value, in one transaction with',
      'the CMS’s bookkeeping. A post that was never published has no row at all,',
      'which is why a visitor cannot reach it.',
      '',
      '## Declared once',
      '',
      'The CMS reads what the application already declared. The post is an Entity,',
      'and one step says which of its fields play a part in the CMS (trimmed):',
      '',
      '```ts',
      'export const Post = Entity.define(',
      "  'Post',",
      '  Schema.Struct({ /* id, title, slug, … */ }),',
      ').pipe(',
      '  Cms.roles({',
      "    label: 'title',",
      "    slug: 'slug',",
      "    published: 'publishedAt',",
      '  }),',
      ')',
      '```',
      '',
      'And one declaration says how posts are authored:',
      '',
      '```ts',
      "export const Posts = Cms.content('posts', {",
      '  entity: Post,',
      '  form: PostForm,',
      '  publish: { create: CreatePost, update: UpdatePost },',
      "  words: { one: 'Post', many: 'Posts' },",
      '})',
      '```',
      '',
      '## A state nobody stores',
      '',
      'The badge beside a post says New, Published, Changed, Unpublished or Archived.',
      'No column holds it. `Cms.state` works it out from facts: is there a row,',
      'may a visitor see it, is there a draft over it, is the entry archived.',
      'A published post with a draft over it is Changed; publish the draft,',
      'and it is Published again. Nothing can fall out of step, because nothing is kept in step.',
      '',
      '## Saving as you type',
      '',
      'The editor, `Cms.editor`, saves once the author rests: here, 800 milliseconds',
      'after the last change. If the save fails, the status line says so and the text stays.',
      'If someone else saved the same post after you opened it, the editor says that too,',
      'and keeps your text on screen rather than writing over theirs.',
      '',
      '## Revisions and a schedule',
      '',
      'Every publish keeps a revision: the value that was published, when, and by whom.',
      'The History beside a post lists them, and restoring one makes it a draft again,',
      'so it is read before it goes live. A post can also be scheduled, and the CMS',
      'publishes it when its time comes, through the same mutation.',
      '',
      '## Who may publish',
      '',
      'Anyone may write here; only an editor may put writing in front of readers.',
      'That rule is one function the server asks before every change of state:',
      '',
      '```ts',
      'allow: (principal, transition) =>',
      "  !['publish', 'schedule', 'unpublish'].includes(transition) ||",
      "  principal?.role === 'editor',",
      '```',
      '',
      'The studio hides the Publish button from a writer, but that is only a courtesy.',
      'The server is what refuses.',
    ],
    3,
  ),
  post(
    'post-builder',
    'Inside the page builder',
    'inside-the-page-builder',
    'Drag a block, undo, copy, preview at a phone’s width: the page builder is state, not a widget. How foldkit-builder and its view fit together.',
    [
      'Open Pages in the studio and choose Home. There is a palette of blocks and the',
      'layers of the page, the page itself, and the settings of whatever is selected.',
      'It looks like a widget. It is a Model.',
      '',
      '## Headless first',
      '',
      '`foldkit-builder` holds the editor’s state and draws nothing: the page, the selection,',
      'which panel a narrow screen shows, and the width the page is previewed at.',
      'Its Messages are what a person can do (select a block, insert one, move it,',
      'change a setting, undo), and its `update` answers them.',
      '',
      '`foldkit-mixins-builder` draws it. Its views name their parts, so this demo styles',
      'every part to match the studio without forking a line of them.',
      '',
      '## Every edit is an Operation',
      '',
      'The Builder does not change the page itself. Each edit becomes an Operation,',
      'and `foldkit-composition` decides whether it may happen. Drop a Heading where',
      'only sections may go, and the edit is refused and the page is unchanged.',
      'The keyboard goes the same way as the pointer: Alt with an arrow moves a layer,',
      'Ctrl+D duplicates it, Delete removes it.',
      '',
      'The page’s history is kept with `foldkit-primitives`, so Ctrl+Z steps back through',
      'the edits and Ctrl+Shift+Z forward again. Copying a block copies everything inside it,',
      'and pasting gives each copy new ids, so a page never holds two blocks with one id.',
      '',
      '## Settings come from the block',
      '',
      'The settings panel is not written block by block. It is a form, built with',
      '`foldkit-form` from the block’s props Schema: a text prop becomes a text field,',
      'a choice of a few values becomes a select, and the Schema’s title and description',
      'become the label and the hint. Each change that reads as a valid value becomes',
      'one Operation. Give a block another prop, and its settings follow.',
      '',
      '## A page is one field of a form',
      '',
      'Saving is not the Builder’s job. In the studio the Builder is one field',
      'of the page’s form, beside its title and its address, and `foldkit-cms` saves',
      'that form as a draft while you work. So a page gets what a post gets:',
      'saving as you type, publishing, revisions and restoring.',
      '',
      '## What you see is drawn by the site',
      '',
      'The canvas is drawn by the site’s own views, so what an author arranges is what',
      'a reader will see. Blocks that read data, like the latest posts, read it on the canvas',
      'as they do on the site. Previewing at a phone’s width shows the layout a phone gets:',
      'the page is its own container, so its layouts answer to its width, not the window’s.',
      '',
      'And an agent can build a page too. It sends the same Operations a person’s',
      'drag sends, and they are checked the same way.',
    ],
    4,
  ),
  post(
    'post-page-as-data',
    'A page is data',
    'a-page-is-data',
    'This page is not HTML. It is a small tree of named blocks, checked against a catalog and drawn by the site’s own views. How foldkit-composition works.',
    [
      'A page builder that stores HTML has already lost. Every redesign is a find and',
      'replace across markup nobody remembers writing, and nothing can tell a good page',
      'from a broken one until someone looks.',
      '',
      '`foldkit-composition` stores what the author chose instead. The home page of this',
      'site is a document like this one, trimmed:',
      '',
      '```json',
      '{',
      '  "format": 1,',
      '  "roots": ["hero", "latest"],',
      '  "nodes": {',
      '    "hero": {',
      '      "block": "Hero",',
      '      "props": { "title": "A blog that explains itself" },',
      '      "regions": { "actions": ["read"] }',
      '    },',
      '    "read": {',
      '      "block": "Button",',
      '      "props": { "label": "Read the blog", "href": "/site/blog" },',
      '      "regions": {}',
      '    },',
      '    "latest": {',
      '      "block": "Section",',
      '      "props": { "heading": "" },',
      '      "regions": { "body": ["posts"] }',
      '    },',
      '    "posts": {',
      '      "block": "PostList",',
      '      "props": { "heading": "Latest writing", "count": 3 },',
      '      "regions": {}',
      '    }',
      '  }',
      '}',
      '```',
      '',
      '## Blocks, regions and a catalog',
      '',
      'A Block is a kind of thing a page may hold: a Hero, a Section, a Heading,',
      'a list of the latest posts. Its props are a Schema, and its regions say what may go inside it:',
      '',
      '```ts',
      "export const Section = Block.define('Section', {",
      '  Props: Schema.Struct({ heading: Schema.String }),',
      '  regions: { body: Region.many({ accepts: [Content.Flow] }) },',
      '  provides: [Content.Section],',
      '})',
      '```',
      '',
      'A Section’s body accepts flow content, such as a Heading or a Text,',
      'and a Section is itself section content, which is what the top of a page accepts.',
      'The Catalog lists the Blocks a site offers. It is code, deployed with the site.',
      'The Document is data, stored in the page’s row. The Catalog says what may exist;',
      'the Document says what does.',
      '',
      '## Checked, not trusted',
      '',
      'Because a page is data, it can be checked. `Composition.validate(Site, page)` lists',
      'every problem with where it is: a block the Catalog does not have, a prop of the',
      'wrong type, a Heading where only sections may go. A page’s publish input carries',
      'that check, so a broken page cannot be published, whoever sends it.',
      '',
      'Edits are data too. Inserting, moving, duplicating or changing a prop is an Operation,',
      'and `Composition.apply` refuses one that would break the page, changing nothing.',
      'That is what the page builder sends when you drag a block.',
      '',
      '## Drawn by the site’s own views',
      '',
      'The site draws a Document with a Renderer: one view per Block. The same Renderer',
      'draws the published page, the studio’s preview and the builder’s canvas.',
      'Change a view, and every page drawn with it changes, including every page',
      'already published.',
      '',
      'When a Block is renamed or a prop reshaped, stored pages move with a migration:',
      '`Composition.migrate` renames blocks and props, or rewrites a node, when a page',
      'is loaded or before it is published.',
    ],
    6,
  ),
  post(
    'post-small-queries',
    'Queries that say what they mean',
    'queries-that-say-what-they-mean',
    'An Entity declared once, screens that name the fields they read, and a query the server compiles from what it means: how Entity, Remote and Crud move this blog’s data.',
    [
      'Every screen of the studio reads data the same way. It says what it needs,',
      'and the Model fills in. No view fetches, and nothing keeps a cache the Model',
      'does not know about.',
      '',
      '## An Entity, declared once',
      '',
      'A post is declared once with `foldkit-entity`, as the fields it has. Everything',
      'else reads that one declaration: the server binds it to a table, the form edits it,',
      'the CMS finds its slug in it, and a view asks for a selection of it:',
      '',
      '```ts',
      'export const PostPage = Entity.select(Post, {',
      '  id: true,',
      '  title: true,',
      '  slug: true,',
      '  excerpt: true,',
      '  cover: true,',
      '  body: true,',
      '  publishedAt: true,',
      '})',
      '```',
      '',
      '## Remote: the server’s facts, in the Model',
      '',
      '`foldkit-remote` keeps what the server owns (posts, pages, drafts) as a cache',
      'inside the Model, each record once. A screen that is showing declares what it reads.',
      'A Subscription turns that into requests for what is missing, the answers come back',
      'as Messages, and one reducer puts them in the Model. When the screen goes,',
      'its need goes with it, and the data can be let go.',
      '',
      'Losing that cache is never losing work: the facts were the server’s,',
      'and asking again is how it recovers. Work that is not yet on the server,',
      'like a draft being typed, is the form’s, and the CMS saves it.',
      '',
      '## A query is a value',
      '',
      'The blog’s index reads the newest published posts. The query is declared',
      'by what it means, not by an address to fetch:',
      '',
      '```ts',
      "export const RecentPosts = Query.define('RecentPosts', {}, () =>",
      '  Query.from(Post).pipe(',
      '    Query.where(Expr.isNotNull(Post.fields.publishedAt)),',
      '    Query.orderBy(Order.desc(Post.fields.publishedAt)),',
      '  ),',
      ')',
      '```',
      '',
      'The server compiles it to SQL with `foldkit-remote-drizzle`, and the client asks',
      'for it by name. There is no endpoint to write, and no second copy of the question',
      'to keep in step. The server still decides what the asker may see: it answers',
      'a visitor and an editor with only what is published.',
      '',
      '## Crud, in brief',
      '',
      'The studio’s list of posts is `foldkit-crud`. A list joins a query to a selection:',
      '',
      '```ts',
      "export const WorklistList = Crud.list('Worklist', {",
      '  query: Cms.Entries,',
      '  selection: EntryRow,',
      '})',
      '```',
      '',
      '`foldkit-mixins-crud` draws it as a table whose rows open the entry. A Crud editor',
      'joins a form to the mutation its value feeds: it loads what the form edits,',
      'fills the form, turns a valid submit into the mutation, and says how it went.',
      'The CMS’s editor has the same shape, with drafts and publishing added.',
      '',
      'Nothing is generated. The application declares the form and the mutation,',
      'and Crud only joins them, so a screen does what those two say and nothing more.',
      'The post on Crud goes further.',
    ],
    8,
  ),
  post(
    'post-styles',
    'Styling a view you did not write',
    'styling-a-view-you-did-not-write',
    'There is no stylesheet in this demo. Views name their parts, and styles attach to the names: how foldkit-mixins styles the studio, the site and the builder.',
    [
      'There is no CSS file in this demo. The studio, the site and the page builder',
      'are styled from TypeScript, and the builder looks like the rest of the studio',
      'though its views come from another package.',
      '',
      '## Views name their parts',
      '',
      'A view drawn with `foldkit-mixins` does not write class names. It draws Slots:',
      'named parts, like a table’s `row` or the builder’s `palette`, each marked as what',
      'it is, such as a control or a part of a layout.',
      '',
      'A Style is a value: declarations, nested rules, a media or container query.',
      '`Style.forSlots(AdminSlots)({ … })` gives a Style for each Slot, and attaching it',
      'to a view gives each Slot a class. A Style’s rules are written when a view',
      'first draws it. This is the “Live” pill in a post’s History:',
      '',
      '```ts',
      'revisionLive: Style.self({',
      '  background: `color-mix(in oklch,',
      '    ${t.success.default} 14%, ${t.surface.base})`,',
      '  borderRadius: t.radius.full,',
      '  color: t.success.ink,',
      '})',
      '```',
      '',
      '## A theme is tokens',
      '',
      'Colours, spacing and type come from a theme’s tokens, the `t` above. The palette',
      'is built from one accent hue in OKLCH, with a lighter accent for dark mode:',
      '',
      '```ts',
      'Theme.oklch({',
      "  accent: { h: 265, c: 0.16, l: '52%', dark: { l: '72%', c: 0.13 } },",
      '})',
      '```',
      '',
      'So the site follows the reader’s light or dark setting with no second set of styles.',
      '',
      '## Styling what you did not write',
      '',
      'The builder’s views live in `foldkit-mixins-builder`. This demo does not fork them:',
      'it attaches its own Styles to the builder’s Slots, so the palette, the layers and the',
      'settings look like the rest of the studio. The table of posts from `foldkit-mixins-crud`',
      'and the forms from `foldkit-mixins-form` are styled the same way.',
      '',
      'Styles sit in cascade layers, so an application’s Style outranks a package’s default',
      'without a contest of selectors. And a layout can answer to the right width:',
      'the builder stacks its panels by its own width, with a container query, so it',
      'stacks in a narrow window and in a narrow pane of a wide one.',
      '',
      '## The first paint',
      '',
      'One stylesheet belongs to no view: the reset, the tokens and the theme.',
      'The build writes it into the page’s HTML, so every page’s first paint already',
      'has the theme’s background, before any script has run.',
    ],
    10,
  ),
]

/** Imports the seed, as `imported` imports each item: the posts, then the pages that point at them. */
export const seed = <E, R>(
  imported: (item: Imported) => Effect.Effect<{ readonly targetId: string }, E, R>,
  now: Date,
): Effect.Effect<void, E, R> =>
  Effect.gen(function* () {
    const ago = (days: number) => new Date(now.getTime() - days * 86_400_000)
    const ids = new Map<string, string>()
    for (const { key, values, daysAgo } of posts) {
      const { targetId } = yield* imported({
        type: 'posts',
        values,
        at: ago(daysAgo),
        entry: `entry-${key}`,
      })
      ids.set(key, targetId)
    }
    const pages = [
      {
        key: 'page-home',
        values: { title: 'Home', slug: 'home', document: home(ids.get('post-page-as-data') ?? '') },
      },
      { key: 'page-about', values: { title: 'About', slug: 'about', document: about } },
    ]
    for (const { key, values } of pages)
      yield* imported({ type: 'pages', values, at: ago(8), entry: `entry-${key}` })
  })
