export {
  NodeId,
  Node,
  type NodeReference,
  Mark,
  Text,
  Paragraph,
  Heading,
  Block,
  Document,
  DocumentLimits,
  DefaultDocumentLimits,
  type UnknownMark,
  findUnknownMarks,
  Position,
  Selection,
  EditorState,
  decodeDocument,
  selectionIsValid,
  inspect,
} from './document.js'
export {
  Operation,
  Transaction,
  Edit,
  type TextTarget,
  apply,
  mapPosition,
  type ChangeSet,
  type PositionStep,
  type SplitStep,
  type RelocateStep,
  type TransactionResult,
} from './transaction.js'
